services:
  db:
    image: postgres:17  # Update if needed
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    # network_mode: host

  odoo:
    build: ./build
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8888:8888"
    command: bash -c "export PYDEVD_DISABLE_FILE_VALIDATION=1 && $${PYTHON_PATH} $${DEBUG_ODOO} $${START_ODOO} $${ODOO_PARAM} && tail -f /dev/null"
    environment:
      PYTHON_PATH: "/usr/local/bin/python3"
      DEBUG_ODOO: "-m debugpy --listen 0.0.0.0:8888"
      START_ODOO: "/opt/odoo/odoo/odoo-bin -c /opt/odoo/<project_repo>/odoo.conf"
      ODOO_PARAM: ""
    volumes:
      - ../:/opt/odoo
      - odoo_data:/home/odoo/.local/share/Odoo
    # network_mode: host

volumes:
  postgresql_data:
  odoo_data:
